(()=>{
'use strict';
const $=id=>document.getElementById(id);
const CRM='pracaPreJaraCRM-v3',EDIT='pracaPreJaraEdits-v1';
let db={},ed={},jobs=[],quick='all',current=null;
try{db=JSON.parse(localStorage.getItem(CRM)||'{}')}catch{}
try{ed=JSON.parse(localStorage.getItem(EDIT)||'{}')}catch{}
const PROFILE=[
  'WordPress/WooCommerce a správa webu/e-shopu',
  'E-commerce produkty, kategórie a obsah',
  'Smart Home/IoT, Home Assistant a technická diagnostika',
  'Reklamácie, troubleshooting a zákaznícka komunikácia',
  'Retail/operations a vedenie tímu',
  'Windows/Microsoft Office a AI nástroje',
  'Samostatnosť, organizácia práce a vodičský preukaz B'
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canon=u=>{try{let x=new URL(u,location.href);['utm_source','utm_medium','utm_campaign','search_id','ref','trk'].forEach(k=>x.searchParams.delete(k));x.hash='';return x.origin+x.pathname+(x.searchParams.toString()?'?'+x.searchParams.toString():'')}catch{return String(u||'').split('#')[0].split('?')[0]}};
function save(){localStorage.setItem(CRM,JSON.stringify(db));localStorage.setItem(EDIT,JSON.stringify(ed))}
function state(id){
  const s=db[id]||(db[id]={read:false,star:false,removed:false,status:'nova',firstViewed:null,lastViewed:null,views:0,note:'',appliedAt:null,followUpAt:null});
  if(s.appliedAt===undefined)s.appliedAt=null;if(s.followUpAt===undefined)s.followUpAt=null;return s;
}
function fmt(x){if(!x)return'—';try{return new Intl.DateTimeFormat('sk-SK',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(x))}catch{return'—'}}
function track(t){t=String(t||'').toLowerCase();if(/wordpress|woocommerce|e.?commerce|e-shop|eshop|web|cms|marketplace|shoptet|shopify|content/.test(t))return'web';if(/techn|it |iot|smart|support|servis|diagnost|hosting|ssl|helpdesk|saas/.test(t))return'tech';if(/administr|office|back.?office|customer|zákazní|hr /.test(t))return'admin';if(/kuriér|vodič|rozvoz|taxi/.test(t))return'driver';if(/sklad|logistik|balič|vžv|retrak/.test(t))return'warehouse';return'other'}
function eng(t){t=String(t||'').toLowerCase();if(/\bb2\b|\bc1\b|komunikatív.*ang|fluent|very good english|veľmi dobr.*nem/.test(t))return'high';if(/angličtin|english|\bb1\b/.test(t))return'unknown';return'ok'}
function sourceTrust(j){if(Number.isFinite(+j.sourceTrust))return +j.sourceTrust;return j.sourceType==='company'?100:j.sourceType==='government'?96:j.sourceType==='jobboard'?90:j.sourceType==='freelance'?76:j.sourceType==='facebook'?58:j.sourceType==='community'?60:72}
function calc(j){let base={web:75,tech:70,admin:58,driver:43,warehouse:35,other:30}[j.track||'other'];let t=(j.title+' '+j.desc).toLowerCase();if(/wordpress|woocommerce|shoptet|e-shop|ecommerce|e-commerce/.test(t))base+=10;if(/home office|remote|hybrid/.test((j.location||'')+' '+(j.form||'')))base+=5;if(j.english==='high')base-=12;if(j.english==='unknown')base-=3;if(sourceTrust(j)<65)base-=4;return Math.max(10,Math.min(99,+j.score||base))}
function normalize(j){
  const o={...j};o.id=String(o.id||canon(o.url)||Math.random());o.url=o.url||'#';o.canonicalUrl=canon(o.url);o.origin=o.origin||'ponuka';o.title=o.title||'';o.company=o.company||'';o.location=o.location||'';o.form=o.form||'';o.pay=o.pay||'';o.start=o.start||'';o.desc=o.desc||'';o.source=o.source||'Zdroj';o.sourceType=o.sourceType||'jobboard';o.sourceTrust=sourceTrust(o);o.track=o.track||track(o.title+' '+o.desc);o.english=o.english||eng((o.engLabel||'')+' '+o.desc);o.engLabel=o.engLabel||({ok:'A2 / bez vyššej',unknown:'treba overiť',high:'vyššia AJ'}[o.english]);o.score=calc(o);o.scoreConfidence=Number.isFinite(+o.scoreConfidence)?+o.scoreConfidence:75;o.status=o.status||'active';o.priority=o.priority||'normal';return o;
}
function parseTop(txt){const d=new DOMParser().parseFromString(txt,'text/html');return[...d.querySelectorAll('.card')].map((c,i)=>{let f=[...c.querySelectorAll('.facts span')].map(x=>x.textContent.trim()),a=c.querySelector('.open'),ey=c.querySelector('.ey')?.textContent||'',cl=c.querySelector('.company')?.textContent||'',parts=cl.split('•');return normalize({id:c.dataset.id||'top-'+i,title:c.querySelector('h3')?.textContent.trim()||'',company:(parts.shift()||'').trim(),location:parts.join('•').trim(),origin:c.dataset.origin||'ponuka',score:+c.dataset.score||0,source:(ey.split('•')[0]||'Zdroj').trim(),sourceType:'jobboard',form:f[0]||'',pay:f[1]||'',start:f[2]||'',engLabel:f[3]||'treba overiť',desc:c.querySelector('.desc')?.textContent.trim()||'',url:a?.href||'#',verifiedAt:'2026-08-26T17:36:00+02:00'})})}
function parseLegacy(txt){const d=new DOMParser().parseFromString(txt,'text/html');return[...d.querySelectorAll('.job-card')].map((c,i)=>{let a=c.querySelector('.apply'),facts={};c.querySelectorAll('.facts>div').forEach(x=>{let b=x.querySelector('b'),s=x.querySelector('span');if(b&&s)facts[b.textContent.trim()]=s.textContent.trim()});let form=facts['💼 Forma']||'',title=c.querySelector('h3')?.textContent.trim()||'',desc=c.querySelector('p')?.textContent.trim()||'',url=a?.href||'#';return normalize({id:'legacy-'+canon(url),title,company:c.querySelector('.company')?.textContent.trim()||'',location:facts['📍 Lokalita']||'',origin:/dohoda|brigád/i.test(form+' '+title)?'brigáda':'ponuka',source:'Profesia – historický snapshot',sourceType:'jobboard',sourceTrust:82,form,pay:facts['💶 Odmena']||'',start:facts['⚡ Nástup']||'',engLabel:'treba overiť',desc,url,verifiedAt:'2026-08-26T09:00:00+02:00',scoreConfidence:55})})}
async function fetchText(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.text()}
async function load(){
  try{
    $('sync').textContent='Kontrolujem JSON feed…';let live=[];
    try{const r=await fetch('jobs-data.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);const data=await r.json();live=(data.jobs||[]).map(normalize);$('feed').textContent='JSON feed • '+(data.updatedAt?fmt(data.updatedAt):'aktuálny')}catch(e){const t=await fetchText('komarena-job-radar-v5.3.html');live=parseTop(t);$('feed').textContent='Fallback v5.3 HTML'}
    let legacy=[];try{legacy=parseLegacy(await fetchText('https://raw.githack.com/Jarekkom86/dochadzka-pro-sk/df4b36286bc50df16b241866108ba77cddbb3454/brigady-ba-2026-08-26.html'))}catch{}
    const map=new Map();legacy.forEach(j=>map.set(j.canonicalUrl,j));live.forEach(j=>map.set(j.canonicalUrl||j.id,j));jobs=[...map.values()].filter(j=>j.status!=='inactive');$('sync').textContent='Zdroj načítaný • '+jobs.length+' unikátnych';render();
  }catch(e){$('sync').textContent='Chyba feedu – posledné lokálne údaje ostávajú';render()}
}
function merged(j){const u=ed[j.id]||{};return{...j,...u,id:j.id,url:j.url,canonicalUrl:j.canonicalUrl,source:j.source,sourceType:j.sourceType,sourceTrust:j.sourceTrust,score:j.score,scoreConfidence:j.scoreConfidence,origin:j.origin,track:j.track,priority:j.priority,verifiedAt:j.verifiedAt,expiresAt:j.expiresAt,status:j.status}}
function opts(v){return['nova','zaujem','reagovane','pohovor','prijate','odmietnute'].map(x=>`<option value="${x}" ${x===v?'selected':''}>${{nova:'Nová',zaujem:'Mám záujem',reagovane:'Reagované',pohovor:'Pohovor',prijate:'Prijaté',odmietnute:'Odmietnuté'}[x]}</option>`).join('')}
function typeLabel(x){return{jobboard:'JOB BOARD',company:'PRIAMO FIRMA',government:'ÚRAD',facebook:'FB VEREJNÉ',freelance:'FREELANCE',community:'KOMUNITA',aggregator:'AGREGÁTOR'}[x]||String(x||'ZDROJ').toUpperCase()}
function originLabel(x){return x==='brigáda'?'BRIGÁDA':x==='zakazka'?'ZÁKAZKA':'PRACOVNÁ PONUKA'}
function meta(j){let a=[];if(j.verifiedAt)a.push('overené '+fmt(j.verifiedAt));if(j.sourceTrust)a.push('zdroj '+j.sourceTrust+'/100');if(j.scoreConfidence)a.push('istota skóre '+j.scoreConfidence+'%');if(j.expiresAt)a.push('končí '+fmt(j.expiresAt));if(j.contact)a.push('kontakt: '+j.contact);return a.join(' • ')}
function card(j0){let j=merged(j0),s=state(j.id),active=['reagovane','pohovor','prijate'].includes(s.status),cls=active?'active':s.read?'seen':'new',badge=active?({reagovane:'REAGOVANÉ',pohovor:'POHOVOR',prijate:'PRIJATÉ'}[s.status]):s.read?'POZERANÁ':'NOVÁ',today=j.priority==='today'||j.score>=90;let workflow='';if(s.appliedAt)workflow+='Reagované '+fmt(s.appliedAt);if(s.followUpAt)workflow+=(workflow?' • ':'')+'follow-up '+fmt(s.followUpAt);return`<article class="card ${cls}" data-id="${esc(j.id)}"><div class="badge">${badge}</div><div class="labels"><span class="label cat">${esc(j.track)}</span><span class="label ${j.origin==='brigáda'?'brig':''}">${originLabel(j.origin)}</span><span class="label">${esc(typeLabel(j.sourceType))}</span><span class="label">${esc(j.source)}</span>${today?'<span class="label cat">🔥 REAGOVAŤ DNES</span>':''}</div><h3>${esc(j.title)}</h3><div class="company">${esc(j.company)}${j.location?' • '+esc(j.location):''}</div><div class="scoreRow"><div class="score"><b>${j.score}</b><small>KomArena Match</small></div><div class="facts"><div class="fact"><span>Forma</span><b>${esc(j.form||'neuvedená')}</b></div><div class="fact"><span>Odmena</span><b>${esc(j.pay||'neuvedená')}</b></div><div class="fact"><span>Nástup</span><b>${esc(j.start||'neuvedený')}</b></div><div class="fact"><span>AJ</span><b>${esc(j.engLabel||'treba overiť')}</b></div></div></div><p class="desc">${esc(j.desc)}</p><div class="view">${esc(meta(j))}</div><div class="crm"><button data-a="star" class="${s.star?'on':''}">${s.star?'★ Obľúbené':'☆ Hviezdička'}</button><button data-a="read">${s.read?'✓ Prečítané':'○ Neprečítané'}</button><select data-a="status">${opts(s.status||'nova')}</select><button data-a="remove">Odstrániť</button></div><div class="view">${s.read?'Prvýkrát '+fmt(s.firstViewed)+' • naposledy '+fmt(s.lastViewed)+' • '+(s.views||0)+'×':'EŠTE SI NEOTVORIL'}${workflow?' • '+esc(workflow):''}</div><textarea class="note" data-a="note" placeholder="Poznámka / kontakt / ďalší krok…">${esc(s.note||'')}</textarea><div class="actions"><button data-a="edit">✎ Upraviť</button><button data-a="react" class="react">✦ Vytvoriť reakciu</button><a data-a="open" class="open" href="${esc(j.url)}" target="_blank" rel="noopener">Otvoriť →</a></div></article>`}
function pass(j0){let j=merged(j0),s=state(j.id),t=(j.title+' '+j.company+' '+j.location+' '+j.desc+' '+j.pay+' '+j.source).toLowerCase();if(s.removed||j.status==='inactive')return false;if(j.expiresAt&&new Date(j.expiresAt)<new Date())return false;if($('q').value&&!t.includes($('q').value.toLowerCase()))return false;if($('origin').value!=='all'&&j.origin!==$('origin').value)return false;if($('track').value!=='all'&&j.track!==$('track').value)return false;if($('eng').value!=='all'&&j.english!==$('eng').value)return false;if(j.score<+$('min').value)return false;if(quick==='new'&&s.read)return false;if(quick==='seen'&&!s.read)return false;if(quick==='star'&&!s.star)return false;if(quick==='top'&&j.score<80)return false;if(quick==='today'&&!(j.priority==='today'||j.score>=90))return false;if(quick==='brigada'&&j.origin!=='brigáda')return false;if(quick==='zakazka'&&j.origin!=='zakazka')return false;if(quick==='web'&&j.track!=='web')return false;if(quick==='tech'&&j.track!=='tech')return false;if(quick==='pipe'&&!['zaujem','reagovane','pohovor','prijate'].includes(s.status))return false;return true}
function render(){let act=jobs.filter(j=>!state(j.id).removed&&j.status!=='inactive'&&(!j.expiresAt||new Date(j.expiresAt)>=new Date()));$('all').textContent=act.length;$('new').textContent=act.filter(j=>!state(j.id).read).length;$('seen').textContent=act.filter(j=>state(j.id).read).length;$('star').textContent=act.filter(j=>state(j.id).star).length;$('topm').textContent=act.filter(j=>j.score>=80).length;$('brig').textContent=act.filter(j=>j.origin==='brigáda').length;$('pipe').textContent=act.filter(j=>['zaujem','reagovane','pohovor','prijate'].includes(state(j.id).status)).length;let x=jobs.filter(pass),mode=$('sort').value;x.sort((a,b)=>mode==='new'?+state(a.id).read-+state(b.id).read:mode==='star'?+state(b.id).star-+state(a.id).star:mode==='view'?new Date(state(b.id).lastViewed||0)-new Date(state(a.id).lastViewed||0):(b.priority==='today')-(a.priority==='today')||b.score-a.score);$('grid').innerHTML=x.map(card).join('');$('empty').style.display=x.length?'none':'block';$('result').textContent=x.length+' výsledkov z '+act.length;document.querySelectorAll('[data-qk]').forEach(n=>n.classList.toggle('on',n.dataset.qk===quick))}
function strength(j){let t=(j.title+' '+j.desc).toLowerCase(),o=[],a=x=>{if(!o.includes(x))o.push(x)};if(/wordpress|woocommerce|e.?commerce|e-shop|web|cms|marketplace|shoptet/.test(t)){a(PROFILE[0]);a(PROFILE[1])}if(/techn|it |iot|smart|support|servis|diagnost|helpdesk|saas/.test(t)){a(PROFILE[2]);a(PROFILE[3])}if(/zákaz|customer|administr|komunik/.test(t))a(PROFILE[3]);if(/manager|operations|retail|prevádz/.test(t))a(PROFILE[4]);a(PROFILE[5]);a(PROFILE[6]);return o.slice(0,5)}
function react(j,short=false){let s=strength(j),t=(j.title+' '+j.desc).toLowerCase(),body=/wordpress|woocommerce|e.?commerce|e-shop|web|cms|shoptet/.test(t)?'Zaujala ma najmä práca s webom alebo e-shopom. Prakticky pracujem s WordPress/WooCommerce, produktovým obsahom, kategóriami a správou webových riešení.':/techn|it |iot|smart|support|servis|helpdesk|saas/.test(t)?'Zaujala ma technická a podporná stránka pozície. Venujem sa diagnostike problémov, Smart Home/IoT, Home Assistantu, technickému servisu a komunikácii so zákazníkmi.':'Zaujala ma praktická náplň pozície a možnosť využiť skúsenosti so zákazníckou komunikáciou, organizáciou práce a riešením problémov.';let intro='Dobrý deň,\n\nreagujem na ponuku „'+j.title+'“'+(j.company?' v spoločnosti '+j.company:'')+'.\n\n'+body;return short?intro+'\n\nRád sa s Vami spojím a preberiem podrobnosti.\n\nS pozdravom\nJaroslav Koman':intro+'\n\nPre túto pozíciu viem ponúknuť najmä:\n- '+s.join('\n- ')+'\n\nRád si s Vami prejdem podrobnosti.\n\nS pozdravom\nJaroslav Koman'}
function cv(j){return'JAROSLAV KOMAN\nCielené CV pre: '+j.title+'\n\nPROFIL\nPrakticky orientovaný technický a prevádzkový profesionál so skúsenosťami so správou WordPress/WooCommerce, e-commerce administráciou, technickou diagnostikou, reklamáciami, zákazníckou komunikáciou, Smart Home/IoT a riadením prevádzky.\n\nKĽÚČOVÉ ZRUČNOSTI\n• '+strength(j).join('\n• ')+'\n\nRELEVANTNÁ PRAX\nWordPress / WooCommerce a e-commerce projekty\nSmart Home / IoT servis a diagnostika\nRetail / operations management – približne 10 rokov manažérskej praxe a vedenie tímu približne 20 ľudí\n\nĎALŠIE\n• Windows / Microsoft Office\n• AI nástroje\n• Vodičský preukaz B'}
function openEdit(j){current=j;let x=merged(j);$('et').value=x.title;$('ec').value=x.company;$('el').value=x.location;$('ep').value=x.pay;$('ef').value=x.form;$('es').value=x.start;$('ee').value=x.english;$('eca').value=x.track;$('ed').value=x.desc;$('editModal').classList.add('show')}
function openReact(j){current=j;let x=merged(j);$('rt').textContent='Reakcia: '+x.title;$('reaction').value=react(x);$('cv').value=cv(x);$('reasons').innerHTML=strength(x).map(a=>'<div>'+esc(a)+'</div>').join('');$('reactModal').classList.add('show')}
$('grid').onclick=e=>{let c=e.target.closest('.card');if(!c)return;let j=jobs.find(x=>x.id===c.dataset.id);if(!j)return;let s=state(j.id),a=e.target.dataset.a;if(a==='star'){s.star=!s.star;save();render()}else if(a==='read'){s.read=!s.read;if(s.read&&!s.firstViewed)s.firstViewed=s.lastViewed=new Date().toISOString();save();render()}else if(a==='remove'){s.removed=true;save();render()}else if(a==='edit')openEdit(j);else if(a==='react')openReact(j);else if(a==='open'){let now=new Date().toISOString();s.read=true;s.firstViewed=s.firstViewed||now;s.lastViewed=now;s.views=(s.views||0)+1;save();setTimeout(render,50)}};
$('grid').onchange=e=>{let c=e.target.closest('.card');if(!c)return;let j=jobs.find(x=>x.id===c.dataset.id);if(!j)return;let s=state(j.id);if(e.target.dataset.a==='status'){s.status=e.target.value;if(s.status==='reagovane'&&!s.appliedAt){s.appliedAt=new Date().toISOString();let f=new Date();f.setDate(f.getDate()+3);s.followUpAt=f.toISOString()}save();render()}};
$('grid').oninput=e=>{let c=e.target.closest('.card');if(!c||e.target.dataset.a!=='note')return;let s=state(c.dataset.id);s.note=e.target.value;save()};
['q','origin','track','eng','min','sort'].forEach(id=>$(id).addEventListener(id==='q'?'input':'change',render));
document.querySelectorAll('[data-qk]').forEach(n=>n.addEventListener('click',()=>{quick=n.dataset.qk;render()}));
document.querySelectorAll('[data-close]').forEach(n=>n.addEventListener('click',()=>$(n.dataset.close).classList.remove('show')));
$('saveEdit').onclick=()=>{if(!current)return;ed[current.id]={title:$('et').value,company:$('ec').value,location:$('el').value,pay:$('ep').value,form:$('ef').value,start:$('es').value,english:$('ee').value,engLabel:{ok:'A2 / bez vyššej',unknown:'treba overiť',high:'vyššia AJ'}[$('ee').value],track:$('eca').value,desc:$('ed').value};save();$('editModal').classList.remove('show');render()};
$('resetEdit').onclick=()=>{if(!current)return;delete ed[current.id];save();$('editModal').classList.remove('show');render()};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('reaction').value);$('copy').textContent='✓ Skopírované';setTimeout(()=>$('copy').textContent='Skopírovať',1200)}catch{}};
$('short').onclick=()=>{if(current)$('reaction').value=react(merged(current),true)};
$('download').onclick=()=>{if(!current)return;let h='<!doctype html><html><meta charset="utf-8"><title>CV Jaroslav Koman</title><body><pre style="font:14px/1.5 Arial;white-space:pre-wrap">'+esc($('cv').value)+'</pre></body></html>',a=document.createElement('a');a.href=URL.createObjectURL(new Blob([h],{type:'text/html'}));a.download='CV-Jaroslav-Koman-'+current.id.replace(/[^a-z0-9]+/gi,'-')+'.html';a.click();URL.revokeObjectURL(a.href)};
$('print').onclick=()=>{let w=open('','_blank');w.document.write('<pre style="font:14px/1.5 Arial;white-space:pre-wrap">'+esc($('cv').value)+'</pre>');w.document.close();w.print()};
$('export').onclick=()=>{let payload={schemaVersion:2,exportedAt:new Date().toISOString(),crm:db,edits:ed};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='KomArena-Job-Radar-CRM-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('restore').onclick=()=>{Object.values(db).forEach(s=>s.removed=false);save();render()};
$('refresh').onclick=load;
setInterval(load,300000);
load();
})();